sonar.projectKey=anthony-openclassroom_projet-6-device34_java
sonar.organization=anthony-openclassroom
sonar.projectName=Workshop Organizer API (Spring Boot)

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

# Exclure le code généré par OpenAPI et les fichiers tiers
sonar.exclusions=src/main/resources/static/**,src/main/java-generated/**
