sonar.projectKey=anthony-openclassroom_projet-6-device34_angular
sonar.organization=anthony-openclassroom
sonar.projectName=Olympic Games Starter (Angular)

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/coverage/**,**/*.js
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.typescript.lcov.reportPaths=coverage/olympic-games-starter/lcov.info
sonar.javascript.lcov.reportPaths=coverage/olympic-games-starter/lcov.info
